image: docker:latest

stages:
  - docker
  - staging
  - production

docker-build-master:
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" --build-arg SSH_PRIV="${SSH_PRIVATE_KEY}" --build-arg SSH_PUB="${SSH_PUBLIC_KEY}" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
    
production-service-update:
  image: debian:buster
  stage: production
  before_script:
    - apt update && apt install -y curl
  script:
    - curl -X POST "$SERVICE_WEBHOOK"
  only:
    - master
    
docker-build:
  stage: docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.gitlab.com
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --build-arg SSH_PRIV="${SSH_PRIVATE_KEY}" --build-arg SSH_PUB="${SSH_PUBLIC_KEY}" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - staging

service-update:
  image: debian:buster
  stage: staging
  before_script:
    - apt update && apt install -y curl
  script:
    - curl -X POST "$TEST_SERVICE_WEBHOOK"
  only:
    - staging
